package pojos;
// Generated 03-feb-2015 11:04:56 by Hibernate Tools 4.3.1



/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private Integer idPregunta;
     private String pregunta;
     private String descripcion;
     private String pathImagen;
     private int examenIdExamen;
     private String respuestaCorrecta;

    public Pregunta() {
    }

    public Pregunta(String pregunta, String descripcion, String pathImagen, int examenIdExamen, String respuestaCorrecta) {
       this.pregunta = pregunta;
       this.descripcion = descripcion;
       this.pathImagen = pathImagen;
       this.examenIdExamen = examenIdExamen;
       this.respuestaCorrecta = respuestaCorrecta;
    }
   
    public Integer getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(Integer idPregunta) {
        this.idPregunta = idPregunta;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPathImagen() {
        return this.pathImagen;
    }
    
    public void setPathImagen(String pathImagen) {
        this.pathImagen = pathImagen;
    }
    public int getExamenIdExamen() {
        return this.examenIdExamen;
    }
    
    public void setExamenIdExamen(int examenIdExamen) {
        this.examenIdExamen = examenIdExamen;
    }
    public String getRespuestaCorrecta() {
        return this.respuestaCorrecta;
    }
    
    public void setRespuestaCorrecta(String respuestaCorrecta) {
        this.respuestaCorrecta = respuestaCorrecta;
    }




}


