package pojos;
// Generated 03-feb-2015 11:04:56 by Hibernate Tools 4.3.1



/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private Integer idRespuesta;
     private String respuesta;
     private int preguntaIdPregunta;

    public Respuesta() {
    }

    public Respuesta(String respuesta, int preguntaIdPregunta) {
       this.respuesta = respuesta;
       this.preguntaIdPregunta = preguntaIdPregunta;
    }
   
    public Integer getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(Integer idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public int getPreguntaIdPregunta() {
        return this.preguntaIdPregunta;
    }
    
    public void setPreguntaIdPregunta(int preguntaIdPregunta) {
        this.preguntaIdPregunta = preguntaIdPregunta;
    }




}


